require('plugin-configurations/telescope')
require('plugin-configurations/treesitter')
require('plugin-configurations/nvim-autopairs')
require('plugin-configurations/comment')
require('plugin-configurations/lsp-installer')
require('plugin-configurations/lsp-handler')
require('plugin-configurations/nvim-cmp')
