# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to check for error in installation
    steps:
      - name: Check for build
        id: build
        uses: actions/dotfiles@v1
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.build.outputs.time }}"
